---
meta:
  name: model
  type: document
keys:
  _id:
    desc: Unique id
    type: object_id
    read: all
    write: app
  link:
    desc: Model link
    read: all
    write: dev
    tags:
    - badge
  goal:
    desc: Model goal
    type: float
    read: all
    write: user
    tags:
    - badge
  auth:
    desc: Model auth
  duration:
    desc: Model duration in days
    type: integer
    default: 60
    read: dev
    write: user
    tags:
    - badge
  expires_at:
    desc: Model expiry date
    type: time
    read: all
    write: dev
    tags:
    - badge
  location_data:
    desc: Model location data
    type: hash
    default: {}
    read: all
    write: user
  lists:
    desc: Model list
    type: array
    default: []
    read: all
    write: user
  reminders_sent:
    desc: Reminders sent?
    type: boolean
    default: false
    read: user
    write: dev
  votes_count:
    desc: Votes count
    type: integer
    default: 0
    read: all
    write: dev
    tags:
    - badge
  parent_id:
    desc: Parent id
    type: object_id
    read: all
    write: dev
  created_at:
    desc: Created at
    type: time
    read: all
    write: dev
  updated_at:
    desc: Updated at
    type: time
    read: all
    write: dev

accessor:
- submittable
- update_expires_at
- skip_before_save
- owner
- validate_campaign_fields
- update_link
scopes:
  featured:
    duration: 60
  nested:
    goal: 10
  finished:
    duration: 60
    goal:
      $gt: 10
  active:
    params:
      - duration
    duration:
      $ne: duration
  ending:
    params:
     - user
    $or:
      - user_id: user.id
      - listener: user.id
      - listener: user.link
    deletors:
      $ne: user.id
