---
meta:
  name: parent
  type: document
keys:
  _id:
    desc: Unique id
    type: object_id
    read: all
    write: app
  house:
    desc: Parent house
    type: string
    read: all
    write: user
  models_count:
    desc: Models count
    type: integer
    default: 0
    read: all
    write: app
  models_featured_count:
    desc: Models featured count
    type: integer
    default: 0
    read: all
    write: app
  models_featured_nested_count:
    desc: Models nested featured count
    type: integer
    default: 0
    read: all
    write: app
  link:
    desc: Link
    read: all
    write: dev

many:
  - models
